### ISSUE TITLE
Ingest document metadata into SOLR

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusSearch#7]
- all document metadata fields from expert client ("Metadata -> Document" tab) should be in document metadata to be used e.g. by Read & Search application
- title, authority, backlink, external ID, hierarchy, author,...

**Comment by fd17** [comment]
A lot of metadata is already ingested during indexing, depending on availability. Added dynamic metadata fields to planned SOLR upgrades list for arbitrary metadata representation in the future.
